### ISSUE TITLE
No way to control a certain executable's volume

### ISSUE THREAD

**Issue by btvoidx** [roblatour/setvol#6]
I would like to target only Spotify, but it appears the controls can only be global. Could such functionality be added?

**Comment by roblatour** [comment]
Yes, you are correct on that, setvol can only change the master volume levels. 

Regarding setting the levels for individual apps, I've taken a run at that before but was unable to get it to work.  

Regardless.  I gave it another shot this morning after reading your feature request, but failed :-(

That being said, I've now opened an issue with the folks who support Naudio; if they can find a way then I should be able to as well.  ref: https://github.com/naudio/NAudio/issues/1058

**Comment by roblatour** [comment]
I just updated SetVol to version 4.0 which now includes the functionality you requested.

There is a new command line option to use for this called 'appaudio'. 

So, for example, if you are running the Spotify Windows app and you want to set its volume to 35 percent, you can now use:
setvol 35 appaudio Spotify

You can also use relative values (for example +10 and -5).  As well the SetVol 'over' feature works with the appaudio command to allow you to smoothly transition the audio change over time.

A few additional notes:

1. the target application that you want to set the audio level for must be running at the time you issue the command

2. in my testing I found that Spotify had to be actually playing something so that SetVol could change its audio levels.  However VLC only had to be running.  So I guess this is going to be hit and miss based on how the target application is designed.

3. it is also possible to run multiple instances of some applications, but not others, on Windows.  This is a completely a function of the target application.  For example you can run multiple instances of VLC at that same time, but you can't do that with Spotifiy.   In any case, if multiple instances of the same app are running such that you can change the audio levels on them, the one command you enter to change the audio level for that applications will be applied to all instances.

4. Internal volume controls within the app my not be automatically adjusted if the audio level is changed by SetVol.  Again, this is a function of the target application.  Regardless the audio levels you hear should be change as expected base on what you have told SetVol to do.

5. if you want to list all the running applications which SetVol can change the audio levels for, you can use the command
   setvol appaudio

6. as with devices, the volume levels you set for an app will survive a reboot.

**Comment by btvoidx** [comment]
Thank you so much for such a quick response! Though I am yet to set everything up :^
